databases:
  - name: zasoby-db
    databaseName: zasoby
    user: zasoby
    region: frankfurt

services:
  - type: pserv
    name: zasoby-redis
    env: docker
    repo: https://github.com/render-examples/redis.git # optional
    region: frankfurt
    disk:
      name: redis-data
      mountPath: /var/lib/redis
      sizeGB: 1 # optional
  - type: web
    name: zasoby
    env: python
    region: frankfurt
    branch: master
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    healthCheckPath: /healthz
    scaling:
      minInstances: 2
      maxInstances: 6
      targetMemoryPercent: 60 # optional if targetCPUPercent is set (valid: 1-90)
      targetCPUPercent: 60 # optional if targetMemory is set (valid: 1-90)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zasoby-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ADMIN_URL
        value: "kijow/"
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
      - key: REDIS_URL
        fromService:
          name: zasoby-redis
          type: pserv
          property: hostport
