databases:
  - name: zasoby
    databaseName: zasoby
    user: zasoby
    region: frankfurt
    plan: free

services:
  - type: web
    name: zasoby
    env: python
    region: frankfurt
    branch: master
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zasoby
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.production"
