# Generated by Django 3.2.12 on 2022-02-27 16:22

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=512, verbose_name='Imię i nazwisko')),
                ('about_info', models.TextField(max_length=512)),
                ('resource', models.CharField(choices=[('home', 'Dom'), ('flat', 'Mieszkanie'), ('room', 'Pokój'), ('couch', 'Kanapa')], max_length=32)),
                ('city_and_zip_code', models.CharField(max_length=128)),
                ('zip_code', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=128)),
                ('people_to_accommodate', models.IntegerField(default=0)),
                ('costs', models.CharField(max_length=256)),
                ('availability', models.DateField(default=django.utils.timezone.now)),
                ('accommodation_length', models.CharField(max_length=512)),
                ('details', models.TextField(max_length=2048)),
                ('transport', models.CharField(choices=[('warsaw', 'Warsaw'), ('poland', 'Poland'), ('none', 'None')], max_length=16)),
                ('phone_number', models.CharField(max_length=16)),
                ('backup_phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('extra', models.CharField(max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
