# Generated by Django 3.2.12 on 2022-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresource',
            name='about_info',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='resource',
            field=models.CharField(choices=[('home', 'Dom'), ('flat', 'Mieszkanie'), ('room', 'Pokój'), ('couch', 'Kanapa')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='zip_code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
