# Generated by Django 3.2.12 on 2022-02-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_housingresource_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresource',
            name='backup_phone_number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='phone_number',
            field=models.CharField(max_length=128),
        ),
    ]
