# Generated by Django 3.2.12 on 2022-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'Świeżak'), ('in_progress', 'W działaniu'), ('success', 'Sukces'), ('cancelled', 'Nieaktualne')], default='new', max_length=32),
        ),
    ]
