# Generated by Django 3.2.12 on 2022-03-01 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220301_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='person_in_charge_old',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='submission',
            name='when',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
