# Generated by Django 3.2.12 on 2022-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220301_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='how_long',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='submission',
            name='people',
            field=models.CharField(max_length=128),
        ),
    ]
