# Generated by Django 3.2.12 on 2022-03-02 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20220302_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='owner',
        ),
        migrations.AddField(
            model_name='housingresource',
            name='note',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='housingresource',
            name='will_pick_up_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='coordinator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coord_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='status',
            field=models.CharField(choices=[('new', 'Świeżak'), ('verified', 'Wiśnia'), ('taken', 'Zajęta'), ('ignore', 'Ignoruj')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'Świeżak'), ('in_progress', 'W działaniu'), ('gone', 'Zniknęła'), ('success', 'Sukces'), ('cancelled', 'Nieaktualne')], default='new', max_length=32),
        ),
    ]
