# Generated by Django 3.2.12 on 2022-03-02 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20220302_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='matcher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source',
            field=models.CharField(choices=[('webform', 'Strona'), ('mail', 'Email'), ('terrain', 'Zachodni'), ('other', 'Inny')], default='webform', max_length=64),
        ),
    ]
