# Generated by Django 3.2.12 on 2022-03-03 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20220302_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-priority', 'created'], 'verbose_name': 'Zgłoszenie', 'verbose_name_plural': 'Zgłoszenia'},
        ),
        migrations.AddField(
            model_name='housingresource',
            name='cherry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='resource',
            field=models.CharField(choices=[('home', 'Dom'), ('flat', 'Mieszkanie'), ('room', 'Pokój'), ('couch', 'Kanapa'), ('mattress', 'Materac')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='status',
            field=models.CharField(choices=[('new', 'Świeżak'), ('taken', 'Zajęta'), ('ignore', 'Ignoruj')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'Świeżak'), ('searching', 'Szukamy'), ('in_progress', 'Host znaleziony'), ('gone', 'Zniknęła'), ('success', 'Sukces'), ('cancelled', 'Nieaktualne')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='transport_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('group', models.CharField(choices=[('remote', 'Zdalna'), ('station', 'Dworzec')], max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
