# Generated by Django 3.2.12 on 2022-03-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220303_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'verbose_name': 'Koordynator', 'verbose_name_plural': 'Koordynatorzy'},
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='address',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='note',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
