# Generated by Django 3.2.12 on 2022-03-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220303_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresource',
            name='people_to_accommodate_raw',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
