# Generated by Django 3.2.12 on 2022-03-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_housingresource_is_dropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresource',
            name='age',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='when_to_call',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
