# Generated by Django 3.2.12 on 2022-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220303_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
