# Generated by Django 3.2.12 on 2022-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_housingresource_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
