# Generated by Django 3.2.12 on 2022-03-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_submission_finished_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='housingresource',
            index=models.Index(fields=['modified'], name='main_housin_modifie_32089d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['modified'], name='main_submis_modifie_843b21_idx'),
        ),
    ]
