# Generated by Django 3.2.12 on 2022-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220304_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingresource',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
