# Generated by Django 3.2.12 on 2022-03-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_objectchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectchange',
            options={'verbose_name': 'Zmiana Rekordu', 'verbose_name_plural': 'Zmiany Rekordów'},
        ),
        migrations.AddField(
            model_name='submission',
            name='should_be_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='coordinator',
            field=models.ForeignKey(blank=True, default=None, help_text='Łącznik', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coord_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='matcher',
            field=models.ForeignKey(blank=True, default=None, help_text='Kto znalazł hosta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='receiver',
            field=models.ForeignKey(blank=True, default=None, help_text='Przyjmujący zgłoszenie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='resource',
            field=models.ForeignKey(blank=True, default=None, help_text='Zasób (Host)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.housingresource'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='when',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Od kiedy potrzebuje', null=True),
        ),
    ]
