# Generated by Django 3.2.12 on 2022-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220308_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresource',
            name='status',
            field=models.CharField(choices=[('new', 'Świeżak'), ('taken', 'Zajęta'), ('calling', 'Dzwonimy'), ('ignore', 'Ignoruj')], default='new', max_length=32),
        ),
    ]
