# Generated by Django 3.2.12 on 2022-03-09 23:23

from django.db import migrations, models
import house_of_refuge.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220310_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingresource',
            name='token',
            field=models.CharField(default=house_of_refuge.main.models.generate_token, max_length=64, unique=True),
        ),
    ]
