# Generated by Django 3.2.12 on 2022-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_housingresource_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingresource',
            name='turtle',
            field=models.BooleanField(default=False, help_text='This host offers longer stay', verbose_name='Turtle'),
        ),
    ]
