# Generated by Django 3.2.12 on 2022-03-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_housingresource_turtle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectchange',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='main.housingresource'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='main.submission'),
        ),
    ]
