# Generated by Django 3.2.12 on 2022-03-16 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='throttle_created_after',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Only submissions created after this date will be counted in calculating throttling limit', verbose_name='Submission Throttling'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='submission_throttling',
            field=models.IntegerField(default=30, help_text='Max number of open/searching submissions. Set to 0 to disable throttling.', verbose_name='Submission Throttling'),
        ),
    ]
