# Generated by Django 3.2.12 on 2022-03-19 13:32

from django.db import migrations, models
import django.utils.timezone
import markdownx.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20220316_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.SlugField(max_length=128)),
                ('menu_title_primary_language', models.CharField(max_length=512)),
                ('menu_title_secondary_language', models.CharField(max_length=512)),
                ('content_primary_language', markdownx.models.MarkdownxField()),
                ('content_secondary_language', markdownx.models.MarkdownxField(help_text='The same content in secondary language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='submission_throttling',
            field=models.IntegerField(default=30, help_text='Max number of open/searching submissions. Set to 0 to disable throttling.', verbose_name='submission throttling'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='throttle_created_after',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Only submissions created after this date will be counted in calculating throttling limit', verbose_name='submission throttling active since'),
        ),
    ]
