# Generated by Django 3.2.12 on 2022-03-19 14:23

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_menupage_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupage',
            name='content_primary_language',
            field=markdownx.models.MarkdownxField(help_text="You can use <a href='https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' target='_blank'>Markdown</a> here."),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='content_secondary_language',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text="You can use <a href='https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' target='_blank'>Markdown</a> here."),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
