# Generated by Django 3.2.12 on 2022-03-20 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import house_of_refuge.main.models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_auto_20220319_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'verbose_name': 'Coordinator', 'verbose_name_plural': 'Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='housingresource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='menupage',
            options={'verbose_name': 'Menu Page', 'verbose_name_plural': 'Menu Pages'},
        ),
        migrations.AlterModelOptions(
            name='objectchange',
            options={'verbose_name': 'Record Change', 'verbose_name_plural': 'Record Changes'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-priority', 'created'], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='group',
            field=models.CharField(choices=[('remote', 'Remote'), ('station', 'Station')], max_length=32, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='about_info',
            field=models.TextField(help_text="how old are you? who do you live with (if you'll host at your place)?", max_length=2048, verbose_name='Something about you'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='accommodation_length',
            field=models.CharField(help_text='For how long can you provide the accomodation?', max_length=1024, verbose_name='Accommodation length'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='address',
            field=models.CharField(help_text='street, building number, appartment number', max_length=512, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='age',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='availability',
            field=models.DateField(default=django.utils.timezone.now, help_text='When can you start providing the accomodation?', verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='backup_phone_number',
            field=models.CharField(blank=True, default='', help_text='An additional contact person', max_length=128, verbose_name='Backup phone number'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='can_take_person_with_pets',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Can accomodate pets?'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='cherry',
            field=models.BooleanField(default=False, verbose_name='Cherry'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='city_and_zip_code',
            field=models.CharField(max_length=512, verbose_name='City and zip code'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='costs',
            field=models.CharField(help_text='Costs of stay - rent, fees, rental costs or free stay', max_length=1024, verbose_name='Costs'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='details',
            field=models.TextField(help_text='A bunch of information about the place - presence of animals, languages spoken by tenants, availability of bed linen and towels, others', max_length=2048, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='Extra details'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='got_hot',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Got hot'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='is_dropped',
            field=models.BooleanField(default=False, verbose_name='Is dropped'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='living_with_pets',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Are there pets in the house?'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='note',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='people_to_accommodate',
            field=models.IntegerField(default=0, help_text='How many people can you support while providing them adequate living conditions?', verbose_name='Max number of people to accomodate'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='people_to_accommodate_raw',
            field=models.CharField(blank=True, default='', help_text='How many people can you support while providing them adequate living conditions?', max_length=1024, verbose_name='Max number of people to accomodate'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='phone_number',
            field=models.CharField(max_length=128, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='resource',
            field=models.CharField(choices=[('home', 'House'), ('flat', 'Apartment'), ('room', 'Room'), ('couch', 'Couch'), ('mattress', 'Mattress')], max_length=1024, verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='status',
            field=models.CharField(choices=[('new', 'Fresh'), ('taken', 'Taken'), ('calling', 'Calling'), ('ignore', 'Ignore'), ('should_delete', 'For deletion')], default='new', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='token',
            field=models.CharField(default=house_of_refuge.main.models.generate_token, max_length=64, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='transport',
            field=models.CharField(choices=[('warsaw', 'Warsaw'), ('poland', 'Poland'), ('none', 'None')], max_length=16, verbose_name='Transport'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='when_to_call',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='When to call?'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='will_pick_up_now',
            field=models.BooleanField(default=False, verbose_name='Will pick the people up'),
        ),
        migrations.AlterField(
            model_name='housingresource',
            name='zip_code',
            field=models.CharField(max_length=8, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='content_primary_language',
            field=markdownx.models.MarkdownxField(help_text="Możesz tu używać <a href='https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' target='_blank'>Markdowna</a>.", verbose_name='Content in the primary language'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='content_secondary_language',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text="Możesz tu używać <a href='https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' target='_blank'>Markdowna</a>.", verbose_name='Content in the secondary language'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='menu_title_primary_language',
            field=models.CharField(max_length=512, verbose_name='Title in the primary language'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='menu_title_secondary_language',
            field=models.CharField(max_length=512, verbose_name='Title in the secondary language'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='change',
            field=models.CharField(max_length=2048, verbose_name='Change'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='main.housingresource', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='main.submission', verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='can_stay_with_pets',
            field=models.CharField(blank=True, help_text='Can the person stay with pets (e.g., due to allergies)?', max_length=512, null=True, verbose_name='Can stay with pets'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contact_person',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='coordinator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coord_subs', to=settings.AUTH_USER_MODEL, verbose_name='Coordinator'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(help_text='Describe the group, age of every person, their relationships (family, friends?), indicate whether it can be broken into smaller groups', max_length=2048, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished at'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='how_long',
            field=models.CharField(help_text='For how long (in days)?', max_length=128, verbose_name='Length of stay'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages that the person speaks', max_length=1024, null=True, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='matcher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_subs', to=settings.AUTH_USER_MODEL, verbose_name='Who found the host'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='note',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='people',
            field=models.CharField(max_length=128, verbose_name='The number of people'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='person_in_charge_old',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Person in charge (legacy)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phone_number',
            field=models.CharField(max_length=128, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='receiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_subs', to=settings.AUTH_USER_MODEL, verbose_name='Receiver of the submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='resource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.housingresource', verbose_name='Resource (Host)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='should_be_deleted',
            field=models.BooleanField(default=False, verbose_name='Should be deleted'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='source',
            field=models.CharField(choices=[('webform', 'Site'), ('mail', 'Email'), ('terrain', 'Terrain'), ('other', 'Other')], default='webform', max_length=64, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'Fresh'), ('searching', 'Searching'), ('in_progress', 'Host found'), ('gone', 'Gone'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='new', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='transport_needed',
            field=models.BooleanField(default=True, verbose_name='Transport needed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='traveling_with_pets',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Traveling with pets'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='when',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Since when the support is needed'),
        ),
    ]
